# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest


before_script:
  - echo "SECRET_KEY=django-insecure-%$ejym00pt^f!)%z=zy$&3y2z5*3_y_1z2pwvhfda0t7l^r9gu" > mysite/mysite/.env
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install -r requirement.txt
    - python mysite/manage.py makemigrations
    - python mysite/manage.py migrate
    - python mysite/manage.py test polls
